# Site settings
author: David
title: "the code horde"
header-img: img/home-bg.png
email: dubywider@gmail.com
copyright_name: David
description: > # this means to ignore newlines until "baseurl:"
  "coding through bootcamp"
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  thesleevecode621

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
